version: '3'
services:

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 5002:8081
    depends_on:
      - redis
  h2:
      container_name: 'h2'
      hostname: 'h2'
      image: 1000kit/h2
      ports:
        - "8181:8181"
        - "1521:1521"
      environment:
      - H2_OPTIONS=-ifNotExists
      - H2_TCP_ALLOW_OTHERS=true
      volumes:
      - ./opt/h2-data

  liquibase:
    container_name: 'liquibase'
    image: liquibase/liquibase:latest
    restart: always
    volumes:
      - ./liquibase-changelogs:/liquibase-changelogs
    command: --changeLogFile=/liquibase-changelogs/db.changelog-master.xml
    depends_on:
      - h2
